# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3773a0deb1c1cb1fb57e8da97fbfa3ea311cbb3a5a4f57cba59f6504b1704642ea109edd32613d8cf28b2c4d0770e2ab43c9ef6357216c6e3aa0f11675dda81f

test:
  secret_key_base: 628a500760a45b1df15dc2d57ef682cd33da7b47f9a50862db478e460920cd420fb90bd8d37efc5a89678bbdb5b83a54b1ed080120c460ad0dab3783316a11c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
